parameters:
#    viva_common.example.class: Vivait\BootstrapBundle\Example

services:
#    viva_common.example:
#        class: %viva_common.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    vivait_twigfilter_extension:
      class: Vivait\BootstrapBundle\Twig\TwigFilterExtension
      tags:
         -  { name: twig.extension }

    vivait_bootstrap.accordion.widget:
      class: Vivait\BootstrapBundle\Form\Type\AccordionType
      tags:
         -  { name: form.type,  alias: accordion }

    vivait_bootstrap.datesince.widget:
      class: Vivait\BootstrapBundle\Form\Type\DateSinceType
      tags:
         -  { name: form.type,  alias: datesince }

    # Custom exception listener
    vivait.bootstrap.exception_listener:
      class: Vivait\BootstrapBundle\EventListener\ExceptionListener
      arguments: ["@templating", "@kernel"]
      tags:
          - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    vivait.bootstrap.menu_builder:
        class: Vivait\BootstrapBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", "@event_dispatcher"]

    vivait.bootstrap.menu.main:
        class: Knp\Menu\MenuItem
        factory_service: vivait.bootstrap.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: bootstrap }

    vivait.bootstrap.listener.entity:
        class: Vivait\BootstrapBundle\EventListener\EntityListener
        arguments:
            session: "@session"
            translator: "@translator"
        tags:
            - { name: kernel.event_listener, event: vivait.entity.created, method: onEntityCreatedEvent }
            - { name: kernel.event_listener, event: vivait.entity.modified, method: onEntityModifiedEvent }
            - { name: kernel.event_listener, event: vivait.entity.deleted, method: onEntityDeletedEvent }
